// Generado por scripts/generar-meta-lecciones.mjs desde lessons.ts.
// No edites a mano: vuelve a correr el script.

/**
 * Lo único de cada lección que sí viaja al navegador: cuánto toma.
 *
 * El resto —los pasos, el error típico, el checklist, el ejemplo y la
 * ilustración— se pide a `/api/lecciones`, que valida el nivel antes de
 * contestar. Aquí no debe aparecer nada más: lo que se agregue a este archivo
 * se descarga sin pagar.
 */
export const MINUTOS_DE_LECCION: Record<string, number> = {
  "Define el tipo de negocio": 15,
  "Identifica a tu cliente ideal": 20,
  "Crea tu propuesta de valor": 15,
  "Investiga a tu competencia": 90,
  "Define tu menú inicial": 40,
  "Valida tu concepto": 120,
  "Define tu zona objetivo": 60,
  "Calcula los metros que necesitas": 45,
  "Visita al menos 5 locales": 180,
  "Negocia renta y depósito": 60,
  "Revisa uso de suelo": 30,
  "Lista tu equipo mínimo": 45,
  "Cotiza la cocina básica": 120,
  "Cotiza refrigeración": 60,
  "Define mobiliario y barra": 45,
  "Lista tus insumos clave": 30,
  "Cotiza 3 proveedores por insumo": 120,
  "Negocia crédito o descuento": 45,
  "Define días de entrega": 20,
  "Define puestos iniciales": 40,
  "Calcula tu nómina mensual": 40,
  "Define horarios y turnos": 30,
  "Plan de capacitación": 90,
  "Elige tus 10 platillos estrella": 30,
  "Define porciones estándar": 120,
  "Diseña la carta": 60,
  "Define tu ticket promedio": 30,
  "Costea 10 platillos": 120,
  "Define tu food cost objetivo": 20,
  "Fija precios de venta": 60,
  "Revisa márgenes cada mes": 30,
  "Aviso de funcionamiento": 60,
  "Licencia municipal": 120,
  "Protección civil": 90,
  "Alta en el SAT": 90,
  "Crea tu Google Maps": 45,
  "Abre tus redes sociales": 60,
  "Define tu promoción de apertura": 45,
  "Consigue 3 aliados locales": 90,
  "Prueba de cocina": 180,
  "Simulacro de servicio": 240,
  "Define tu fecha de apertura": 30,
  "Checklist del día 1": 45,
  "Prepara tu página de Facebook e Instagram": 30,
  "Toma las 9 fotos que sí venden": 60,
  "Instala el Administrador de anuncios": 20,
  "Tu primer anuncio: 3 km a la redonda": 40,
  "Define cuánto invertir al día": 25,
  "Escribe el texto que hace que vengan": 30,
  "Lee tus resultados sin volverte loco": 20,
  "Contesta y convierte en WhatsApp": 25,
  "Repite lo que funcionó": 30,
  "Reclama tu Perfil de Empresa": 30,
  "Llena tu perfil al 100%": 45,
  "Sube las fotos que te posicionan": 60,
  "Escribe tu descripción y tus servicios": 40,
  "Carga tu menú y tus productos": 50,
  "Aprende a detectar al cliente satisfecho": 25,
  "Crea tu QR de reseñas": 25,
  "Coloca el QR donde sí funciona": 30,
  "Enseña a tu equipo la frase exacta": 30,
  "Responde todas las reseñas": 30,
  "Publica novedades cada semana": 20,
  "Define el puesto antes de buscar": 20,
  "Pon tus tres filtros obligatorios": 15,
  "Publica en los grupos de bolsa de trabajo": 30,
  "Pide la solicitud de empleo de papelería": 15,
  "Verifica que viva a 5 km": 10,
  "Confirma sus 6 meses de cocina": 15,
  "Haz la entrevista corta": 25,
  "Ponle prueba en cocina de una hora": 60,
  "Deja claro el sueldo y el horario": 20,
  "Dale de alta como se debe": 40,
  "Enséñale su primera semana": 45,
  "Evalúa a los 30 días": 25,
  "Decide si el delivery te conviene": 20,
  "Reúne tus papeles para el alta": 25,
  "Date de alta en Rappi paso a paso": 35,
  "Date de alta en UberEats y DiDi Food": 30,
  "Negocia tu comisión antes de firmar": 20,
  "Calcula tu precio de delivery": 25,
  "Decide qué platillos NO van en la app": 20,
  "Costea tu empaque de verdad": 25,
  "Arma tu carta digital con fotos": 40,
  "Configura horario, zona y tiempos": 25,
  "Entiende las promociones y quién las paga": 20,
  "Lee tu estado de cuenta y reclama": 20,
  "Empuja el pedido directo por WhatsApp": 30,
  "Revisa cada mes si sigue conviniendo": 20,
  "Mide y sube de nivel": 25
};

/** Minutos de una lección. El de reserva es el mismo de `FALLBACK_LESSON`. */
export const minutosDeLeccion = (titulo: string): number => MINUTOS_DE_LECCION[titulo] ?? 20;
